### ISSUE TITLE
Linked In Follow link

### ISSUE THREAD

**Issue by Marfa** [tolgaergin/social#2]
Linked In follow me link is broken.

**Comment by tolgaergin** [comment]
When listing your social accounts, for some websites such as 
LinkedIn, Evernote, Paypal, Windows, Flud, AIM, Yahoo 

Example:
Some LinkedIn profiles URL are like that "my.linkedin.com/pub/jack-cunningham/4/936/537"
and Some LinkedIn profiles URL is pretty good "ca.linkedin.com/in/marthajack"

You need to write url address without "http://" or "https://" Because, these websites doesnt have regular url.
TRUE: linkedin: 'ca.linkedin.com/in/marthajack'
